server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Wolroys/configuration_Xproject
          username: Wolroys
          password: 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
          default-label: main